name: 'PR CI (Maven)'

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - "*.txt"
      - ".github/**" 
      - "!.github/workflows/pr_ci.yml"

env:
  DEFAULT_MUSIC_FOLDER: /tmp/music
  EXCLUDED_TEST_GROUPS:

jobs:
  build:
    runs-on: ubuntu-latest
    env: ${{ matrix.cfg.env }}
    services: ${{ matrix.cfg.services }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ matrix.cfg.jdk }}
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Setup ffmpeg
        id: setup-ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - run: mkdir -p ${DEFAULT_MUSIC_FOLDER}
      - run: ${{ matrix.cfg.run }}
        if: matrix.cfg.executeManualcommand
      - name: Build with Maven
        run: mvn -DexcludedGroups=${EXCLUDED_TEST_GROUPS} -Ddocker.testing.default-music-folder=${DEFAULT_MUSIC_FOLDER} verify -B -P integration-test

    strategy:
      fail-fast: false
      matrix:
        cfg:
          - jdk: 17
            services: {}
            env: {}
          - jdk: 21
            services: {}
            env: {}
          # external dbs
          - jdk: 21
            services:
              postgres:
                image: 'postgres@sha256:1414298ea93186123a6dcf872f778ba3bd2347edcbd2f31aa7bb2d9814ff5393' # postgres:15.13-alpine
                ports:
                  - 5432:5432
                env:
                  POSTGRES_PASSWORD: pass
            env:
              spring_datasource_url: 'jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified&raiseExceptionOnSilentRollback=false'
              spring_datasource_username: postgres
              spring_datasource_password: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
          - jdk: 21
            services:
              postgres:
                image: 'postgres@sha256:578ca5c8452c08a4e0f5e65b55dce5e1812fe63c8fee40ea837641031598e51e' # postgres:14.1-alpine
                ports:
                  - 5432:5432
                env:
                  POSTGRES_PASSWORD: pass
            env:
              spring_datasource_url: 'jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified&raiseExceptionOnSilentRollback=false'
              spring_datasource_username: postgres
              spring_datasource_password: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
 
          - jdk: 21
            db: 'mysql:8.0'
            executeManualCommand: true
            run: >
              docker pull ${DB};
              docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=${spring_datasource_password} -e MYSQL_DATABASE=airsonic -p 3306:3306 ${DB} --character-set-server=utf8mb4 --collation-server=utf8mb4_bin;
              until docker run --rm --link mysql:ms ${DB} mysql --host=ms --user=${spring_datasource_username} --password=${spring_datasource_password} -e 'SELECT 1' &> /dev/null; do sleep 1; done;
            services: {}
            services2:
              mysql:
                image: 'mysql@sha256:7dcddc01f13bab2f15cde676d44d01f61fc9f99fe7785e86196dfc07d358ae2b' # mysql:8.0
                ports:
                  - 3306:3306
                env:
                  MYSQL_DATABASE: airsonic
                  MYSQL_ROOT_PASSWORD: pass
            env:
              DB: 'mysql:8.0'
              spring_datasource_url: 'jdbc:mysql://localhost:3306/airsonic'
              spring_datasource_username: root
              spring_datasource_password: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
          - jdk: 21
            db: 'mariadb:10.5'
            executeManualCommand: true
            run: >
              docker pull ${DB};
              docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=${spring_datasource_password} -e MYSQL_DATABASE=airsonic -p 3306:3306 ${DB} --character-set-server=utf8mb4 --collation-server=utf8mb4_bin;
              until docker run --rm --link mysql:ms ${DB} mysql --host=ms --user=${spring_datasource_username} --password=${spring_datasource_password} -e 'SELECT 1' &> /dev/null; do sleep 1; done;
            services: {}
            services2:
              mysql:
                image: 'mariadb@sha256:a530aeeefd82f4fa5150f391b6c75462140904780338766f6b03acecb1cca3ce' # mariadb:10.5
                ports:
                  - 3306:3306
                env:
                  MYSQL_DATABASE: airsonic
                  MYSQL_ROOT_PASSWORD: pass
            env:
              DB: 'mariadb:10.5'
              spring_datasource_url: 'jdbc:mariadb://localhost:3306/airsonic'
              spring_datasource_username: root
              spring_datasource_password: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
